spring.application.name=SecurityLombokValidation

spring.datasource.url=jdbc:mysql://localhost:3306/seclomval
spring.datasource.username=root
spring.datasource.password=Jaya_2323

spring.jpa.hibernate.ddl-auto=update
